sudo: required
language: bash

branches:
  except:
    - /^\d+.\d+.\d+$/

services:
  - docker

# fixme: read permissions issue
#cache:
#  directories:
#    - $HOME/.cargo

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - CI_CARGO_CACHE=" -v $HOME/.cargo:/root/.cargo "

before_install:
  - export CI_BUILD_NUMBER=$(if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then echo $CI_BUILD_NUMBER; else echo "${TRAVIS_BUILD_NUMBER}-SNAPSHOT"; fi)
  - echo "CI_BUILD_NUMBER=${CI_BUILD_NUMBER}"
  - if [ -n "$DOCKER_LOGIN" ]; then docker login --username $DOCKER_LOGIN --password $DOCKER_PASS; fi

script:
  # https://github.com/travis-ci/travis-ci/issues/6934
  - travis_wait 30 sleep infinity & make $(if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then echo publish; else echo package; fi)

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(make version)
  - echo "GIT_TAG=$GIT_TAG"
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/jobs/$TRAVIS_JOB_ID"
    || true
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git push -q --tags || true
