[package]
name = "jira-transit"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies]
afterparty = { git = "https://github.com/softprops/afterparty" }
env_logger = "0.3"
hyper = "0.9"
log = "0.3"
